#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label media
yabai -m space 4 --label social
yabai -m space 5 --label games
yabai -m space 6 --label else

shift + cmd - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.70           \
    window_opacity               on				\
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          0              \
    window_border_radius         0				\
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  5				\
    bottom_padding               5				\
    left_padding                 5				\
    right_padding                5				\
    window_gap                   5				\
    layout                       bsp            \

yabai -m rule --add app="^Alacritty$" space=code
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^(Discord|Telegram|WhatsApp)$" space=social
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^(StarCraft II|Battle.net)$" space=games

yabai -m config --space media layout stack
yabai -m config --space social layout stack
yabai -m config --space games layout stack

echo "yabai configuration loaded.."
