#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label media
yabai -m space 4 --label social

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               on             \
    window_shadow                off            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.70           \
    window_opacity               on				\
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_radius         0				\
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  5				\
    bottom_padding               5				\
    left_padding                 5				\
    right_padding                5				\
    window_gap                   5				\
    layout                       bsp            \

yabai -m rule --add app="^Alacritty$" space=code
yabai -m rule --add app="^(Firefox|Arc)$" space=web
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^(Discord|Telegram|WhatsApp)$" space=social
yabai -m rule --add app="^(System Settings|FaceTime|QuickTime Player)$" manage=off

echo "yabai configuration loaded.."
