alias v='nvim'
alias ll='ls -lhars name'
alias lt='ls -L 3 -s extension --tree'
alias ta='tmux attach -t'
alias tq='tmux kill-session -t'
alias e='exit'
alias note='scripta write ~/.config/Note/riflessione'
alias todo='scripta write ~/.config/Note/todo'
alias blog='f() { if [ "$1" = "" ]; then set -- $1 "pagina"; fi; scripta write ~/.config/Note/"$1"; }; f'
alias note='scripta write ./note'
alias job='scripta write /Users/carlorosso/Documents/4BConsulting/Notes/carlo-log'

